export const ITEMS_DATA = [
  {
    id: 1,
    label: 'ACC Gold cement',
    type: 'Cement',
    price: 320,
    discount: true,
    discountedPrice: 160,
    imageSrc: require('../assests/CementBag.png'),
    Brand: 'ACC',
    Grade: 'OPC 33',
    Weight: '20 Kg',
    Rating: '1 ⭐️',
  },
  {
    id: 2,
    label: 'ACC Concrete Plus',
    type: 'Cement',
    price: 280,
    discount: true,
    discountedPrice: 180,
    imageSrc: require('../assests/CementBag.png'),
    Brand: 'ACC',
    Grade: 'UOPC 43',
    Weight: '30 Kg',
    Rating: '2 ⭐️',
  },
  {
    id: 3,
    label: 'ACC F2R Cement',
    type: 'Cement',
    price: 350,
    discount: true,
    discountedPrice: 280,
    imageSrc: require('../assests/CementBag.png'),
    Brand: 'ACC',
    Grade: 'OPC 53',
    Weight: '40 Kg',
    Rating: '3 ⭐️',
  },
  {
    id: 4,
    label: 'Ultra Tech Cement',
    type: 'Cement',
    price: 300,
    discount: true,
    discountedPrice: 150,
    imageSrc: require('../assests/CementBag.png'),
    Brand: 'Ultra Tech',
    Grade: 'OPC 33',
    Weight: '50 Kg',
    Rating: '4 ⭐️',
  },
  {
    id: 5,
    label: 'Ultra Tech Cement Super',
    type: 'Cement',
    price: 400,
    discount: true,
    discountedPrice: 400,
    imageSrc: require('../assests/CementBag.png'),
    Brand: 'Ultra Tech',
    Grade: 'UOPC 43',
    Weight: '20 Kg',
    Rating: '5 ⭐️',
  },
  {
    id: 6,
    label: 'Birla Cement',
    type: 'Cement',
    price: 400,
    discount: true,
    discountedPrice: 200,
    imageSrc: require('../assests/CementBag.png'),
    Brand: 'Ultra Tech',
    Grade: 'OPC 33',
    Weight: '20 Kg',
    Rating: '3 ⭐️',
  },
  {
    id: 7,
    label: 'Bharathi Cement',
    type: 'Cement',
    price: 400,
    discount: true,
    discountedPrice: 190,
    imageSrc: require('../assests/CementBag.png'),
    Brand: 'Bharathi',
    Grade: 'UOPC 43',
    Weight: '30 Kg',
    Rating: '2 ⭐️',
  },
  {
    id: 8,
    label: 'Bharathi Ultra Fast',
    type: 'Cement',
    price: 400,
    discount: true,
    discountedPrice: 270,
    imageSrc: require('../assests/CementBag.png'),
    Brand: 'Bharathi',
    Grade: 'UOPC 43',
    Weight: '20 Kg',
    Rating: '1 ⭐️',
  },
  {
    id: 9,
    label: 'Bharathi PPC Cement',
    type: 'Cement',
    price: 400,
    discount: true,
    discountedPrice: 350,
    imageSrc: require('../assests/CementBag.png'),
    Brand: 'Bharathi',
    Grade: 'OPC 33',
    Weight: '50 Kg',
    Rating: '5 ⭐️',
  },
  {
    id: 10,
    label: 'Infra Market Cement',
    type: 'Cement',
    price: 400,
    discount: true,
    discountedPrice: 190,
    imageSrc: require('../assests/CementBag.png'),
    Brand: 'Infra Market',
    Grade: 'OPC 53',
    Weight: '40 Kg',
    Rating: '2 ⭐️',
  },
  {
    id: 11,
    label: 'Infra Market Ultra Fast',
    type: 'Cement',
    price: 400,
    discount: true,
    discountedPrice: 270,
    imageSrc: require('../assests/CementBag.png'),
    Brand: 'Infra Market',
    Grade: 'UOPC 43',
    Weight: '20 Kg',
    Rating: '1 ⭐️',
  },
  {
    id: 12,
    label: 'Infra Market PPC Cement',
    type: 'Cement',
    price: 400,
    discount: true,
    discountedPrice: 350,
    imageSrc: require('../assests/CementBag.png'),
    Brand: 'Infra Market',
    Grade: 'OPC 33',
    Weight: '50 Kg',
    Rating: '5 ⭐️',
  },
  {
    id: 13,
    label: 'Sagar Cement',
    type: 'Cement',
    price: 400,
    discount: true,
    discountedPrice: 190,
    imageSrc: require('../assests/CementBag.png'),
    Brand: 'Sagar',
    Grade: 'OPC 53',
    Weight: '30 Kg',
    Rating: '2 ⭐️',
  },
  {
    id: 14,
    label: 'Sagar Ultra Fast',
    type: 'Cement',
    price: 400,
    discount: true,
    discountedPrice: 270,
    imageSrc: require('../assests/CementBag.png'),
    Brand: 'Sagar',
    Grade: 'UOPC 43',
    Weight: '20 Kg',
    Rating: '1 ⭐️',
  },
  {
    id: 15,
    label: 'Sagar PPC Cement',
    type: 'Cement',
    price: 400,
    discount: true,
    discountedPrice: 350,
    imageSrc: require('../assests/CementBag.png'),
    Brand: 'Sagar',
    Grade: 'OPC 33',
    Weight: '40 Kg',
    Rating: '5 ⭐️',
  },
];
